apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-broker
  labels:
    app: telemetry-broker
spec:
  selector:
    matchLabels:
      app:  telemetry-broker
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: telemetry-broker
        version: v1
    spec:
      containers:
        - image: apollin/telemetry-broker:v1
          imagePullPolicy: Always
          name: telemetry-broker
          env:
            - name: JAEGER_HOST
              value: jaeger-agent.istio-system.svc.cluster.local
            - name: JAEGER_SERVICE_NAME
              value: telemetry-broker
            - name: PROMETHEUS_URL
              value: prometheus.istio-system.svc.cluster.local

          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: telemetry-broker
  labels:
    app: telemetry-broker
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: telemetry-broker